version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run:
          name: Install Server Dependency
          command: |
            sudo apt-get update
            sudo apt-get install git zip unzip subversion
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install production dependencies
          command: |
            composer validate
            composer install --prefer-dist
  php_lint:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run:
          name: Install Server Dependency
          command: |
            sudo apt-get update
            sudo apt-get install git zip unzip subversion
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Composer dependencies
          command: |
            composer validate
            composer install --prefer-dist
      - run:
          name: Lint PHP
          command: composer run lint:phpcs
  php_unit_integration:
    docker:
      - image: cimg/php:8.1-node
      - image: cimg/mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run:
          name: Install Server Dependency
          command: |
            sudo apt-get update
            sudo apt-get install git zip unzip subversion default-mysql-client
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
      - run:
          name: Install Composer dependencies
          command: |
            composer validate
            composer install --prefer-dist
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit --testsuite=integration
  php_unit_default:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run:
          name: Install Server Dependency
          command: |
            sudo apt-get update
            sudo apt-get install git zip unzip subversion
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Composer dependencies
          command: |
            composer validate
            composer install --prefer-dist
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit --testsuite=unit
# Orchestrate our job run sequence.
workflows:
  version: 2
  build_and_test:
    jobs:
      - php_lint:
          filters:
            branches:
              ignore: /.*-built/
      - php_unit_integration:
          filters:
            branches:
              ignore: /.*-built/
      - php_unit_default:
          filters:
            branches:
              ignore: /.*-built/
      - build:
          requires:
            - php_lint
            - php_unit_integration
            - php_unit_default
